### ISSUE TITLE
markdown documentation quick reference in editor?

### ISSUE THREAD

**Issue by sotto** [tagspaces/tagspaces-extensions#6]
a link to markdown documentation or quickreferencepage in the editor with common markdown markup would be handy for non-fluent-markdown-writers.

**Comment by janvanl** [comment]
Hi,
i have a video that will not play in the extension. After some searching i found that Windows Film (W10) says it needs a codec MPEG-H Part2/HEVC (H.265) (hevc) which should not be installed in Windows.

My question, Does the extension use Windows-codecs or its own codecs.

The video was made with a rather new dashcam.

Regards,
Jan

**Comment by uggrock** [comment]
Hi,
TagSpaces use the codecs integrated in the underlying Electron/Chromium infrastructure. So if you can play a given files format in a recent Chrome browser, it should also by playable in TagSpaces.

Greeting
